### ISSUE TITLE
Locomotive MK2 Benefits?

### ISSUE THREAD

**Issue by Pioneer420** [DellAquila/DoubleCargoWagon#1]
I compared the vanilla and MK2 pulling/stopping power and found that the MK2 does have better stopping power but it has the same pulling power as the vanilla even though it consumes 50% more power. What is another benefit of using the MK2 over the vanilla considering it is 15 times more expensive to build?

**Comment by DellAquila** [comment]
I was able only to change the Torque. So its great to going up with a lot of cargo! :)  I think....

**Comment by Pioneer420** [comment]
> I was able only to change the Torque. So its great to going up with a lot of cargo! :) I think....

That is so strange cause I tested to see if it had more torque with a loaded upward incline (Ramp 8m x 2m & 10x Freights) and both the vanilla and MK2 were even. I guess it is a game mechanic problem.
